# Generated by Django 4.2.1 on 2023-07-04 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('adjacent_places', models.ManyToManyField(blank=True, related_name='adj_places', to='search.places')),
            ],
        ),
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destination_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_places', to='search.places')),
                ('source_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_places', to='search.places')),
            ],
        ),
    ]
